name: Build binaries on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller

      - name: Build with PyInstaller (spec)
        shell: bash
        run: |
          if [ -f "PyClickr.spec" ]; then
            pyinstaller "PyClickr.spec"
          elif [ -f "pyclickr.spec" ]; then
            pyinstaller "pyclickr.spec"
          else
            echo "No spec found; falling back to onefile build"
            pyinstaller --onefile --windowed --name PyClickr src/pyclickr/app.py
          fi

      - name: Locate EXE path
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path dist -Filter *.exe -Recurse | Select-Object -First 1
          if (-not $exe) { Write-Error "No EXE found in dist/*"; exit 1 }
          "OUT=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "OUT_BASENAME=$($exe.Name)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Found EXE: $($exe.FullName)"

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.OUT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
